	//basic map config with custom fills, mercator projection
	var map = new Datamap({
		scope: 'world',
		element: document.getElementById('container1'),
		projection: 'mercator',
		geographyConfig: {
			highlightBorderColor: '#666666',
			popupTemplate: function(geography, data) {
				return "<div class='hoverinfo'>Visitors: " + data.visitors +'</div>'
		},
		highlightBorderWidth: 1
		},

		fills: {
			defaultFill: '#00ffff',
			USA: '#ff00ff',
			DEU: '#5fa0ff',
			GBR: '#45baff',
			JPN: '#1ce3ff',
			CHN: '#39c6ff',
			CHE: '#22ddff',
			KOR: '#16e9ff',
			TUR: '#0cf3ff',
			BRA: '#29d6ff',
			CAN: '#28d7ff',
			IND: '#23dcff',
			AUS: '#13ecff',
			POL: '#0ff0ff',
			AUT: '#0ef1ff',
			FRA: '#18e7ff',
			MEX: '#0ff0ff',
			DNK: '#09f6ff',
			ESP: '#10efff',
			ITA: '#10efff',
			NLD: '#0cf3ff',
			COL: '#08f7ff',
			SGP: '#0af5ff',
			RUS: '#08f7ff',
			SWE: '#09f6ff',
			BEL: '#08f7ff',
			SVK: '#03fcff',
			CHN: '#07f8ff',
			ISR: '#06f9ff',
			FIN: '#04fbff',
			PAK: '#05faff',
			SAU: '#05faff',
			GTM: '#01feff',
			NZL: '#01feff',
			CMR: '#03fcff',
			ZAF: '#03fcff',
			CHL: '#02fdff',
			PRT: '#02fdff',
			NOR: '#02fdff',
			BOL: '#00ffff',
			HKG: '#02fdff',
			IRN: '#03fcff',
			ARG: '#02fdff',
			CZE: '#02fdff',
			MYS: '#03fcff',
			UKR: '#01feff',
			GRC: '#02fdff',
			ROU: '#01feff',
			IRL: '#01feff',
			VEN: '#01feff',
			LTU: '#01feff',
			HUN: '#01feff',
			IDN: '#01feff',
			PHL: '#01feff',
			EGY: '#01feff',
			ARE: '#01feff',
			SVN: '#01feff',
			THA: '#01feff',
			ARM: '#00ffff',
			MAR: '#01feff',
			VNM: '#00ffff',
			DZA: '#00ffff',
			NGA: '#00ffff',
			SRB: '#00ffff',
			EST: '#00ffff',
			BGR: '#00ffff',
			HRV: '#00ffff',
			MLT: '#00ffff',
			PER: '#00ffff',
			BGD: '#00ffff',
			QAT: '#00ffff',
			ISL: '#00ffff',
			BLR: '#00ffff',
			LUX: '#00ffff',
			YEM: '#00ffff',
			NPL: '#00ffff',
			TUN: '#00ffff',
			PRI: '#00ffff',
			BTN: '#00ffff',
			ETH: '#00ffff',
			KAZ: '#00ffff',
			LVA: '#00ffff',
			OMN: '#00ffff',
			BHR: '#00ffff',
			CRI: '#00ffff',
			CPV: '#00ffff',
			CYP: '#00ffff',
			GEO: '#00ffff',
			IRQ: '#00ffff',
			JOR: '#00ffff',
			KWT: '#00ffff',
			LIE: '#00ffff',
			PAN: '#00ffff',
			TTO: '#00ffff',
			ALB: '#00ffff',
			BIH: '#00ffff',
			ECU: '#00ffff',
			JAM: '#00ffff',
			KEN: '#00ffff',
			KHM: '#00ffff',
			LBN: '#00ffff',
			MNE: '#00ffff',
			MKD: '#00ffff',
			MMR: '#00ffff',
			MNG: '#00ffff',
			MAC: '#00ffff',
			MDV: '#00ffff',
			NER: '#00ffff',
			PSE: '#00ffff',
			PRY: '#00ffff',
			SEN: '#00ffff',
			SXM: '#00ffff',
			UGA: '#00ffff',
			URY: '#00ffff',
			VCT: '#00ffff',
			ZMB: '#00ffff',
		},

		data: {
			USA: {fillKey: 'USA', visitors: 3256 },
			DEU: {fillKey: 'DEU', visitors: 1209 },
			GBR: {fillKey: 'GBR', visitors: 885 },
			JPN: {fillKey: 'JPN', visitors: 368 },
			CHN: {fillKey: 'CHN', visitors: 725 },
			CHE: {fillKey: 'CHE', visitors: 434 },
			KOR: {fillKey: 'KOR', visitors: 284 },
			TUR: {fillKey: 'TUR', visitors: 162 },
			BRA: {fillKey: 'BRA', visitors: 527 },
			CAN: {fillKey: 'CAN', visitors: 518 },
			IND: {fillKey: 'IND', visitors: 454 },
			AUS: {fillKey: 'AUS', visitors: 248 },
			POL: {fillKey: 'POL', visitors: 195 },
			AUT: {fillKey: 'AUT', visitors: 190 },
			FRA: {fillKey: 'FRA', visitors: 314 },
			MEX: {fillKey: 'MEX', visitors: 193 },
			DNK: {fillKey: 'DNK', visitors: 126 },
			ESP: {fillKey: 'ESP', visitors: 208 },
			ITA: {fillKey: 'ITA', visitors: 211 },
			NLD: {fillKey: 'NLD', visitors: 160 },
			COL: {fillKey: 'COL', visitors: 107 },
			SGP: {fillKey: 'SGP', visitors: 137 },
			RUS: {fillKey: 'RUS', visitors: 105 },
			SWE: {fillKey: 'SWE', visitors: 116 },
			BEL: {fillKey: 'BEL', visitors: 103 },
			SVK: {fillKey: 'SVK', visitors: 40 },
			CHN: {fillKey: 'CHN', visitors: 91 },
			ISR: {fillKey: 'ISR', visitors: 86 },
			FIN: {fillKey: 'FIN', visitors: 58 },
			PAK: {fillKey: 'PAK', visitors: 64 },
			SAU: {fillKey: 'SAU', visitors: 69 },
			GTM: {fillKey: 'GTM', visitors: 20 },
			NZL: {fillKey: 'NZL', visitors: 24 },
			CMR: {fillKey: 'CMR', visitors: 41 },
			ZAF: {fillKey: 'ZAF', visitors: 47 },
			CHL: {fillKey: 'CHL', visitors: 37 },
			PRT: {fillKey: 'PRT', visitors: 37 },
			NOR: {fillKey: 'NOR', visitors: 34 },
			BOL: {fillKey: 'BOL', visitors: 11 },
			HKG: {fillKey: 'HKG', visitors: 34 },
			IRN: {fillKey: 'IRN', visitors: 46 },
			ARG: {fillKey: 'ARG', visitors: 38 },
			CZE: {fillKey: 'CZE', visitors: 32 },
			MYS: {fillKey: 'MYS', visitors: 39 },
			UKR: {fillKey: 'UKR', visitors: 25 },
			GRC: {fillKey: 'GRC', visitors: 33 },
			ROU: {fillKey: 'ROU', visitors: 23 },
			IRL: {fillKey: 'IRL', visitors: 24 },
			VEN: {fillKey: 'VEN', visitors: 25 },
			LTU: {fillKey: 'LTU', visitors: 15 },
			HUN: {fillKey: 'HUN', visitors: 24 },
			IDN: {fillKey: 'IDN', visitors: 15 },
			PHL: {fillKey: 'PHL', visitors: 18 },
			EGY: {fillKey: 'EGY', visitors: 15 },
			ARE: {fillKey: 'ARE', visitors: 18 },
			SVN: {fillKey: 'SVN', visitors: 16 },
			THA: {fillKey: 'THA', visitors: 16 },
			ARM: {fillKey: 'ARM', visitors: 7 },
			MAR: {fillKey: 'MAR', visitors: 13 },
			VNM: {fillKey: 'VNM', visitors: 11 },
			DZA: {fillKey: 'DZA', visitors: 12 },
			NGA: {fillKey: 'NGA', visitors: 5 },
			SRB: {fillKey: 'SRB', visitors: 12 },
			EST: {fillKey: 'EST', visitors: 6 },
			BGR: {fillKey: 'BGR', visitors: 6 },
			HRV: {fillKey: 'HRV', visitors: 8 },
			MLT: {fillKey: 'MLT', visitors: 3 },
			PER: {fillKey: 'PER', visitors: 6 },
			BGD: {fillKey: 'BGD', visitors: 4 },
			QAT: {fillKey: 'QAT', visitors: 6 },
			ISL: {fillKey: 'ISL', visitors: 4 },
			BLR: {fillKey: 'BLR', visitors: 3 },
			LUX: {fillKey: 'LUX', visitors: 4 },
			YEM: {fillKey: 'YEM', visitors: 2 },
			NPL: {fillKey: 'NPL', visitors: 2 },
			TUN: {fillKey: 'TUN', visitors: 1 },
			PRI: {fillKey: 'PRI', visitors: 3 },
			BTN: {fillKey: 'BTN', visitors: 3 },
			ETH: {fillKey: 'ETH', visitors: 2 },
			KAZ: {fillKey: 'KAZ', visitors: 1 },
			LVA: {fillKey: 'LVA', visitors: 2 },
			OMN: {fillKey: 'OMN', visitors: 2 },
			BHR: {fillKey: 'BHR', visitors: 2 },
			CRI: {fillKey: 'CRI', visitors: 1 },
			CPV: {fillKey: 'CPV', visitors: 1 },
			CYP: {fillKey: 'CYP', visitors: 2 },
			GEO: {fillKey: 'GEO', visitors: 1 },
			IRQ: {fillKey: 'IRQ', visitors: 2 },
			JOR: {fillKey: 'JOR', visitors: 2 },
			KWT: {fillKey: 'KWT', visitors: 2 },
			LIE: {fillKey: 'LIE', visitors: 0 },
			PAN: {fillKey: 'PAN', visitors: 1 },
			TTO: {fillKey: 'TTO', visitors: 1 },
			ALB: {fillKey: 'ALB', visitors: 1 },
			BIH: {fillKey: 'BIH', visitors: 0 },
			ECU: {fillKey: 'ECU', visitors: 1 },
			JAM: {fillKey: 'JAM', visitors: 1 },
			KEN: {fillKey: 'KEN', visitors: 1 },
			KHM: {fillKey: 'KHM', visitors: 1 },
			LBN: {fillKey: 'LBN', visitors: 1 },
			MNE: {fillKey: 'MNE', visitors: 0 },
			MKD: {fillKey: 'MKD', visitors: 0 },
			MMR: {fillKey: 'MMR', visitors: 1 },
			MNG: {fillKey: 'MNG', visitors: 1 },
			MAC: {fillKey: 'MAC', visitors: 0 },
			MDV: {fillKey: 'MDV', visitors: 1 },
			NER: {fillKey: 'NER', visitors: 1 },
			PSE: {fillKey: 'PSE', visitors: 0 },
			PRY: {fillKey: 'PRY', visitors: 0 },
			SEN: {fillKey: 'SEN', visitors: 1 },
			SXM: {fillKey: 'SXM', visitors: 1 },
			UGA: {fillKey: 'UGA', visitors: 1 },
			URY: {fillKey: 'URY', visitors: 1 },
			VCT: {fillKey: 'VCT', visitors: 1 },
			ZMB: {fillKey: 'ZMB', visitors: 1 },
		}
	})

