
//basic map config with custom fills, mercator projection
var map = new Datamap({
	scope: 'world',
	element: document.getElementById('container1'),
	projection: 'mercator',
	geographyConfig: {
		highlightBorderColor: '#666666',
		popupTemplate: function(geography, data) {
			if (data != null) return "<div class='hoverinfo'>" + geography.properties.name+': '+data.visitors +'</div>'
	},
	highlightBorderWidth: 1
	},
fills: { 
defaultFill: '#CCCCCC', 
MUS: '#f7fbff',
CMR: '#f6faff',
QAT: '#f7fbff',
FRO: '#f7fbff',
CHE: '#e7f0fa',
TZA: '#f7fbff',
MLI: '#f7fbff',
ROU: '#f6faff',
CHN: '#dce9f6',
SLV: '#f7fbff',
MTQ: '#f7fbff',
GTM: '#f7fbff',
MYS: '#f5fafe',
AUS: '#e6f0f9',
EGY: '#f5fafe',
GUM: '#f7fbff',
UZB: '#f7fbff',
HUN: '#f5f9fe',
PHL: '#f5fafe',
VNM: '#f6faff',
GRC: '#f5fafe',
MLT: '#f7fbff',
CRI: '#f7fbff',
HKG: '#f5f9fe',
EST: '#f7fbff',
ITA: '#e8f1fa',
GBR: '#b0d2e7',
ZMB: '#f7fbff',
GHA: '#f7fbff',
MKD: '#f7fbff',
MAR: '#f6faff',
SWE: '#eff6fc',
MDA: '#f7fbff',
PAK: '#f5f9fe',
BLZ: '#f7fbff',
BRA: '#dae8f6',
LBY: '#f7fbff',
IRL: '#f5fafe',
CZE: '#f5fafe',
KEN: '#f7fbff',
DZA: '#f6faff',
AZE: '#f7fbff',
MNG: '#f7fbff',
SGP: '#eff6fc',
UKR: '#f5f9fe',
THA: '#f6faff',
BMU: '#f7fbff',
IDN: '#f6faff',
BFA: '#f7fbff',
TJK: '#f7fbff',
BIH: '#f7fbff',
SWZ: '#f7fbff',
LIE: '#f7fbff',
BHS: '#f7fbff',
NGA: '#f7fbff',
RUS: '#edf4fc',
BGD: '#f7fbff',
DNK: '#f1f7fd',
LKA: '#f7fbff',
LUX: '#f7fbff',
HRV: '#f6faff',
GEO: '#f7fbff',
SVN: '#f6faff',
LBR: '#f7fbff',
PRI: '#f7fbff',
ISR: '#eff6fc',
IND: '#d9e7f5',
GRD: '#f7fbff',
CUW: '#f7fbff',
UGA: '#f7fbff',
BEL: '#f3f8fe',
USA: '#08306b',
JPN: '#d9e7f5',
FIN: '#f5f9fe',
MEX: '#edf4fc',
ARG: '#f5f9fe',
KWT: '#f7fbff',
ALB: '#f7fbff',
CIV: '#f7fbff',
IRN: '#f2f7fd',
CHL: '#f5f9fe',
ETH: '#f7fbff',
KOR: '#edf4fc',
MDG: '#f7fbff',
LSO: '#f7fbff',
LVA: '#f7fbff',
TUR: '#eef5fc',
SEN: '#f7fbff',
DEU: '#92c4de',
IRQ: '#f7fbff',
ECU: '#f7fbff',
POL: '#eef5fc',
GUY: '#f7fbff',
NPL: '#f7fbff',
BEN: '#f7fbff',
SAU: '#f5fafe',
URY: '#f7fbff',
JOR: '#f7fbff',
ISL: '#f7fbff',
ARE: '#f6faff',
FRA: '#d9e8f5',
PRT: '#f5fafe',
LBN: '#f7fbff',
PER: '#f6faff',
MAC: '#f7fbff',
TKM: '#f7fbff',
ESP: '#e9f2fa',
SYR: '#f7fbff',
TUN: '#f7fbff',
BGR: '#f6faff',
COL: '#edf4fc',
NIC: '#f7fbff',
BHR: '#f7fbff',
LTU: '#f7fbff',
NZL: '#f5f9fe',
PAN: '#f7fbff',
OMN: '#f7fbff',
SVK: '#f6faff',
ARM: '#f7fbff',
CAN: '#dae8f6',
GRL: '#f7fbff',
DOM: '#f7fbff',
REU: '#f7fbff',
SDN: '#f7fbff',
TWN: '#f1f7fd',
BOL: '#f7fbff',
TTO: '#f7fbff',
CYP: '#f7fbff',
NLD: '#e9f2fa',
NOR: '#f5fafe',
KAZ: '#f7fbff',
CUB: '#f7fbff',
VEN: '#f7fbff',
SRB: '#f7fbff',
ZAF: '#f5f9fe',
BLR: '#f7fbff',
AUT: '#ebf3fb',
HND: '#f7fbff',
MMR: '#f7fbff',
DMA: '#f7fbff',
},data: { 
MUS: {fillKey: 'MUS', visitors: 4, country: " Mauritius " },
CMR: {fillKey: 'CMR', visitors: 42, country: " Cameroon " },
QAT: {fillKey: 'QAT', visitors: 5, country: " Qatar " },
FRO: {fillKey: 'FRO', visitors: 1, country: " Faroe Islands " },
CHE: {fillKey: 'CHE', visitors: 559, country: " Switzerland " },
TZA: {fillKey: 'TZA', visitors: 3, country: " Tanzania, United Republic of " },
MLI: {fillKey: 'MLI', visitors: 2, country: " Mali " },
ROU: {fillKey: 'ROU', visitors: 33, country: " Romania " },
CHN: {fillKey: 'CHN', visitors: 927, country: " China " },
SLV: {fillKey: 'SLV', visitors: 1, country: " El Salvador " },
MTQ: {fillKey: 'MTQ', visitors: 1, country: " Martinique " },
GTM: {fillKey: 'GTM', visitors: 5, country: " Guatemala " },
MYS: {fillKey: 'MYS', visitors: 72, country: " Malaysia " },
AUS: {fillKey: 'AUS', visitors: 602, country: " Australia " },
EGY: {fillKey: 'EGY', visitors: 70, country: " Egypt " },
GUM: {fillKey: 'GUM', visitors: 1, country: " Guam " },
UZB: {fillKey: 'UZB', visitors: 1, country: " Uzbekistan " },
HUN: {fillKey: 'HUN', visitors: 84, country: " Hungary " },
PHL: {fillKey: 'PHL', visitors: 67, country: " Philippines " },
VNM: {fillKey: 'VNM', visitors: 33, country: " Viet Nam " },
GRC: {fillKey: 'GRC', visitors: 74, country: " Greece " },
MLT: {fillKey: 'MLT', visitors: 18, country: " Malta " },
CRI: {fillKey: 'CRI', visitors: 10, country: " Costa Rica " },
HKG: {fillKey: 'HKG', visitors: 101, country: " Hong Kong " },
EST: {fillKey: 'EST', visitors: 14, country: " Estonia " },
ITA: {fillKey: 'ITA', visitors: 516, country: " Italy " },
GBR: {fillKey: 'GBR', visitors: 2143, country: " United Kingdom " },
ZMB: {fillKey: 'ZMB', visitors: 3, country: " Zambia " },
GHA: {fillKey: 'GHA', visitors: 9, country: " Ghana " },
MKD: {fillKey: 'MKD', visitors: 2, country: " Macedonia, Republic of " },
MAR: {fillKey: 'MAR', visitors: 39, country: " Morocco " },
SWE: {fillKey: 'SWE', visitors: 272, country: " Sweden " },
MDA: {fillKey: 'MDA', visitors: 4, country: " Moldova, Republic of " },
PAK: {fillKey: 'PAK', visitors: 85, country: " Pakistan " },
BLZ: {fillKey: 'BLZ', visitors: 1, country: " Belize " },
BRA: {fillKey: 'BRA', visitors: 983, country: " Brazil " },
LBY: {fillKey: 'LBY', visitors: 2, country: " Libya " },
IRL: {fillKey: 'IRL', visitors: 68, country: " Ireland " },
CZE: {fillKey: 'CZE', visitors: 64, country: " Czech Republic " },
KEN: {fillKey: 'KEN', visitors: 25, country: " Kenya " },
DZA: {fillKey: 'DZA', visitors: 30, country: " Algeria " },
AZE: {fillKey: 'AZE', visitors: 3, country: " Azerbaijan " },
MNG: {fillKey: 'MNG', visitors: 4, country: " Mongolia " },
SGP: {fillKey: 'SGP', visitors: 279, country: " Singapore " },
UKR: {fillKey: 'UKR', visitors: 92, country: " Ukraine " },
THA: {fillKey: 'THA', visitors: 46, country: " Thailand " },
BMU: {fillKey: 'BMU', visitors: 1, country: " Bermuda " },
IDN: {fillKey: 'IDN', visitors: 51, country: " Indonesia " },
BFA: {fillKey: 'BFA', visitors: 1, country: " Burkina Faso " },
TJK: {fillKey: 'TJK', visitors: 5, country: " Tajikistan " },
BIH: {fillKey: 'BIH', visitors: 5, country: " Bosnia and Herzegovina " },
SWZ: {fillKey: 'SWZ', visitors: 1, country: " Swaziland " },
LIE: {fillKey: 'LIE', visitors: 1, country: " Liechtenstein " },
BHS: {fillKey: 'BHS', visitors: 2, country: " Bahamas " },
NGA: {fillKey: 'NGA', visitors: 9, country: " Nigeria " },
RUS: {fillKey: 'RUS', visitors: 344, country: " Russian Federation " },
BGD: {fillKey: 'BGD', visitors: 19, country: " Bangladesh " },
DNK: {fillKey: 'DNK', visitors: 234, country: " Denmark " },
LKA: {fillKey: 'LKA', visitors: 14, country: " Sri Lanka " },
LUX: {fillKey: 'LUX', visitors: 26, country: " Luxembourg " },
HRV: {fillKey: 'HRV', visitors: 38, country: " Croatia " },
GEO: {fillKey: 'GEO', visitors: 7, country: " Georgia " },
SVN: {fillKey: 'SVN', visitors: 30, country: " Slovenia " },
LBR: {fillKey: 'LBR', visitors: 1, country: " Liberia " },
PRI: {fillKey: 'PRI', visitors: 13, country: " Puerto Rico " },
ISR: {fillKey: 'ISR', visitors: 270, country: " Israel " },
IND: {fillKey: 'IND', visitors: 1044, country: " India " },
GRD: {fillKey: 'GRD', visitors: 1, country: " Grenada " },
CUW: {fillKey: 'CUW', visitors: 1, country: " Curaçao " },
UGA: {fillKey: 'UGA', visitors: 2, country: " Uganda " },
BEL: {fillKey: 'BEL', visitors: 144, country: " Belgium " },
USA: {fillKey: 'USA', visitors: 6732, country: " United States " },
JPN: {fillKey: 'JPN', visitors: 1036, country: " Japan " },
FIN: {fillKey: 'FIN', visitors: 105, country: " Finland " },
MEX: {fillKey: 'MEX', visitors: 360, country: " Mexico " },
ARG: {fillKey: 'ARG', visitors: 92, country: " Argentina " },
KWT: {fillKey: 'KWT', visitors: 4, country: " Kuwait " },
ALB: {fillKey: 'ALB', visitors: 1, country: " Albania " },
CIV: {fillKey: 'CIV', visitors: 6, country: " Côte d'Ivoire " },
IRN: {fillKey: 'IRN', visitors: 206, country: " Iran, Islamic Republic of " },
CHL: {fillKey: 'CHL', visitors: 104, country: " Chile " },
ETH: {fillKey: 'ETH', visitors: 13, country: " Ethiopia " },
KOR: {fillKey: 'KOR', visitors: 359, country: " Korea, Republic of " },
MDG: {fillKey: 'MDG', visitors: 1, country: " Madagascar " },
LSO: {fillKey: 'LSO', visitors: 2, country: " Lesotho " },
LVA: {fillKey: 'LVA', visitors: 22, country: " Latvia " },
TUR: {fillKey: 'TUR', visitors: 334, country: " Turkey " },
SEN: {fillKey: 'SEN', visitors: 2, country: " Senegal " },
DEU: {fillKey: 'DEU', visitors: 2732, country: " Germany " },
IRQ: {fillKey: 'IRQ', visitors: 10, country: " Iraq " },
ECU: {fillKey: 'ECU', visitors: 5, country: " Ecuador " },
POL: {fillKey: 'POL', visitors: 301, country: " Poland " },
GUY: {fillKey: 'GUY', visitors: 1, country: " Guyana " },
NPL: {fillKey: 'NPL', visitors: 2, country: " Nepal " },
BEN: {fillKey: 'BEN', visitors: 2, country: " Benin " },
SAU: {fillKey: 'SAU', visitors: 66, country: " Saudi Arabia " },
URY: {fillKey: 'URY', visitors: 8, country: " Uruguay " },
JOR: {fillKey: 'JOR', visitors: 4, country: " Jordan " },
ISL: {fillKey: 'ISL', visitors: 6, country: " Iceland " },
ARE: {fillKey: 'ARE', visitors: 37, country: " United Arab Emirates " },
FRA: {fillKey: 'FRA', visitors: 1000, country: " France " },
PRT: {fillKey: 'PRT', visitors: 67, country: " Portugal " },
LBN: {fillKey: 'LBN', visitors: 2, country: " Lebanon " },
PER: {fillKey: 'PER', visitors: 27, country: " Peru " },
MAC: {fillKey: 'MAC', visitors: 4, country: " Macao " },
TKM: {fillKey: 'TKM', visitors: 1, country: " Turkmenistan " },
ESP: {fillKey: 'ESP', visitors: 489, country: " Spain " },
SYR: {fillKey: 'SYR', visitors: 2, country: " Syrian Arab Republic " },
TUN: {fillKey: 'TUN', visitors: 15, country: " Tunisia " },
BGR: {fillKey: 'BGR', visitors: 28, country: " Bulgaria " },
COL: {fillKey: 'COL', visitors: 344, country: " Colombia " },
NIC: {fillKey: 'NIC', visitors: 1, country: " Nicaragua " },
BHR: {fillKey: 'BHR', visitors: 2, country: " Bahrain " },
LTU: {fillKey: 'LTU', visitors: 16, country: " Lithuania " },
NZL: {fillKey: 'NZL', visitors: 80, country: " New Zealand " },
PAN: {fillKey: 'PAN', visitors: 3, country: " Panama " },
OMN: {fillKey: 'OMN', visitors: 2, country: " Oman " },
SVK: {fillKey: 'SVK', visitors: 38, country: " Slovakia " },
ARM: {fillKey: 'ARM', visitors: 6, country: " Armenia " },
CAN: {fillKey: 'CAN', visitors: 989, country: " Canada " },
GRL: {fillKey: 'GRL', visitors: 1, country: " Greenland " },
DOM: {fillKey: 'DOM', visitors: 4, country: " Dominican Republic " },
REU: {fillKey: 'REU', visitors: 1, country: " Réunion " },
SDN: {fillKey: 'SDN', visitors: 1, country: " Sudan " },
TWN: {fillKey: 'TWN', visitors: 223, country: " Taiwan, Province of China " },
BOL: {fillKey: 'BOL', visitors: 21, country: " Bolivia, Plurinational State of " },
TTO: {fillKey: 'TTO', visitors: 3, country: " Trinidad and Tobago " },
CYP: {fillKey: 'CYP', visitors: 13, country: " Cyprus " },
NLD: {fillKey: 'NLD', visitors: 476, country: " Netherlands " },
NOR: {fillKey: 'NOR', visitors: 64, country: " Norway " },
KAZ: {fillKey: 'KAZ', visitors: 5, country: " Kazakhstan " },
CUB: {fillKey: 'CUB', visitors: 2, country: " Cuba " },
VEN: {fillKey: 'VEN', visitors: 24, country: " Venezuela, Bolivarian Republic of " },
SRB: {fillKey: 'SRB', visitors: 1, country: " Serbia " },
ZAF: {fillKey: 'ZAF', visitors: 83, country: " South Africa " },
BLR: {fillKey: 'BLR', visitors: 12, country: " Belarus " },
AUT: {fillKey: 'AUT', visitors: 408, country: " Austria " },
HND: {fillKey: 'HND', visitors: 6, country: " Honduras " },
MMR: {fillKey: 'MMR', visitors: 3, country: " Myanmar " },
DMA: {fillKey: 'DMA', visitors: 1, country: " Dominica " },
}
})
