
//basic map config with custom fills, mercator projection
var map = new Datamap({
	scope: 'world',
	element: document.getElementById('container1'),
	projection: 'mercator',
	geographyConfig: {
		highlightBorderColor: '#666666',
		popupTemplate: function(geography, data) {
			if (data != null) return "<div class='hoverinfo'>" + geography.properties.name+': '+data.visitors +'</div>'
	},
	highlightBorderWidth: 1
	},
fills: { 
defaultFill: '#CCCCCC', 
ETH: '#c7dbef',
ALB: '#c7dbef',
QAT: '#c7dbef',
NZL: '#c4daee',
ZAF: '#c4daee',
JOR: '#c7dbef',
BFA: '#c7dbef',
MNG: '#c7dbef',
LIE: '#c7dbef',
GUM: '#c7dbef',
CZE: '#c4daee',
SEN: '#c7dbef',
CUB: '#c7dbef',
OMN: '#c7dbef',
LTU: '#c7dbef',
IND: '#a1cbe2',
BMU: '#c7dbef',
IRL: '#c4daee',
JPN: '#a1cbe2',
MMR: '#c7dbef',
UZB: '#c7dbef',
PAK: '#c4daee',
USA: '#08306b',
CYP: '#c7dbef',
LVA: '#c6dbef',
ECU: '#c7dbef',
FRA: '#a3cce3',
AUS: '#b2d2e8',
GRD: '#c7dbef',
LKA: '#c7dbef',
BEL: '#c2d9ee',
GTM: '#c7dbef',
PRT: '#c4daee',
CMR: '#c6dbef',
LUX: '#c6dbef',
TUN: '#c7dbef',
CIV: '#c7dbef',
ARE: '#c6dbef',
DZA: '#c6dbef',
COL: '#bad6eb',
SAU: '#c4daee',
URY: '#c7dbef',
HKG: '#c3daee',
ISL: '#c7dbef',
TJK: '#c7dbef',
TWN: '#bfd8ed',
SDN: '#c7dbef',
CUW: '#c7dbef',
POL: '#bcd7eb',
MKD: '#c7dbef',
SVN: '#c6dbef',
GUY: '#c7dbef',
AZE: '#c7dbef',
RUS: '#bad6eb',
HRV: '#c6dbef',
CRI: '#c7dbef',
EST: '#c7dbef',
BLR: '#c7dbef',
KEN: '#c6dbef',
MAR: '#c6dbef',
MDG: '#c7dbef',
MUS: '#c7dbef',
PHL: '#c4daee',
IDN: '#c6dbef',
AUT: '#b8d5ea',
IRQ: '#c7dbef',
MLT: '#c6dbef',
HUN: '#c4daee',
PRI: '#c7dbef',
BRA: '#a4cce3',
GBR: '#71b1d7',
BIH: '#c7dbef',
PAN: '#c7dbef',
MAC: '#c7dbef',
MDA: '#c7dbef',
CHL: '#c3daee',
BEN: '#c7dbef',
CAN: '#a4cce3',
BOL: '#c6dbef',
TZA: '#c7dbef',
REU: '#c7dbef',
DOM: '#c7dbef',
GRC: '#c4daee',
DEU: '#5aa2cf',
VNM: '#c6dbef',
MLI: '#c7dbef',
ESP: '#b5d4e9',
KAZ: '#c7dbef',
TUR: '#bad6eb',
DMA: '#c7dbef',
MEX: '#bad6eb',
KWT: '#c7dbef',
ISR: '#bdd7ec',
NGA: '#c7dbef',
ARM: '#c7dbef',
TKM: '#c7dbef',
CHE: '#b3d3e8',
LBR: '#c7dbef',
EGY: '#c4daee',
GHA: '#c7dbef',
ARG: '#c3daee',
LBN: '#c7dbef',
SGP: '#bdd7ec',
LBY: '#c7dbef',
THA: '#c6dbef',
FRO: '#c7dbef',
SVK: '#c6dbef',
NOR: '#c4daee',
UKR: '#c3daee',
IRN: '#bfd8ed',
BGD: '#c6dbef',
UGA: '#c7dbef',
SWZ: '#c7dbef',
LSO: '#c7dbef',
SYR: '#c7dbef',
ZMB: '#c7dbef',
FIN: '#c3daee',
GEO: '#c7dbef',
BGR: '#c6dbef',
HND: '#c7dbef',
NPL: '#c7dbef',
SLV: '#c7dbef',
ROU: '#c6dbef',
TTO: '#c7dbef',
KOR: '#bad6eb',
BHS: '#c7dbef',
DNK: '#bed8ec',
ITA: '#b4d3e9',
VEN: '#c6dbef',
NIC: '#c7dbef',
MYS: '#c4daee',
SRB: '#c7dbef',
GRL: '#c7dbef',
BHR: '#c7dbef',
MTQ: '#c7dbef',
PER: '#c6dbef',
CHN: '#a5cde3',
BLZ: '#c7dbef',
NLD: '#b5d4e9',
SWE: '#bdd7ec',
},data: { 
ETH: {fillKey: 'ETH', visitors: 13, country: " Ethiopia " },
ALB: {fillKey: 'ALB', visitors: 1, country: " Albania " },
QAT: {fillKey: 'QAT', visitors: 5, country: " Qatar " },
NZL: {fillKey: 'NZL', visitors: 80, country: " New Zealand " },
ZAF: {fillKey: 'ZAF', visitors: 83, country: " South Africa " },
JOR: {fillKey: 'JOR', visitors: 4, country: " Jordan " },
BFA: {fillKey: 'BFA', visitors: 1, country: " Burkina Faso " },
MNG: {fillKey: 'MNG', visitors: 4, country: " Mongolia " },
LIE: {fillKey: 'LIE', visitors: 1, country: " Liechtenstein " },
GUM: {fillKey: 'GUM', visitors: 1, country: " Guam " },
CZE: {fillKey: 'CZE', visitors: 64, country: " Czech Republic " },
SEN: {fillKey: 'SEN', visitors: 2, country: " Senegal " },
CUB: {fillKey: 'CUB', visitors: 2, country: " Cuba " },
OMN: {fillKey: 'OMN', visitors: 2, country: " Oman " },
LTU: {fillKey: 'LTU', visitors: 16, country: " Lithuania " },
IND: {fillKey: 'IND', visitors: 1044, country: " India " },
BMU: {fillKey: 'BMU', visitors: 1, country: " Bermuda " },
IRL: {fillKey: 'IRL', visitors: 68, country: " Ireland " },
JPN: {fillKey: 'JPN', visitors: 1036, country: " Japan " },
MMR: {fillKey: 'MMR', visitors: 3, country: " Myanmar " },
UZB: {fillKey: 'UZB', visitors: 1, country: " Uzbekistan " },
PAK: {fillKey: 'PAK', visitors: 85, country: " Pakistan " },
USA: {fillKey: 'USA', visitors: 6732, country: " United States " },
CYP: {fillKey: 'CYP', visitors: 13, country: " Cyprus " },
LVA: {fillKey: 'LVA', visitors: 22, country: " Latvia " },
ECU: {fillKey: 'ECU', visitors: 5, country: " Ecuador " },
FRA: {fillKey: 'FRA', visitors: 1000, country: " France " },
AUS: {fillKey: 'AUS', visitors: 602, country: " Australia " },
GRD: {fillKey: 'GRD', visitors: 1, country: " Grenada " },
LKA: {fillKey: 'LKA', visitors: 14, country: " Sri Lanka " },
BEL: {fillKey: 'BEL', visitors: 144, country: " Belgium " },
GTM: {fillKey: 'GTM', visitors: 5, country: " Guatemala " },
PRT: {fillKey: 'PRT', visitors: 67, country: " Portugal " },
CMR: {fillKey: 'CMR', visitors: 42, country: " Cameroon " },
LUX: {fillKey: 'LUX', visitors: 26, country: " Luxembourg " },
TUN: {fillKey: 'TUN', visitors: 15, country: " Tunisia " },
CIV: {fillKey: 'CIV', visitors: 6, country: " Côte d'Ivoire " },
ARE: {fillKey: 'ARE', visitors: 37, country: " United Arab Emirates " },
DZA: {fillKey: 'DZA', visitors: 30, country: " Algeria " },
COL: {fillKey: 'COL', visitors: 344, country: " Colombia " },
SAU: {fillKey: 'SAU', visitors: 66, country: " Saudi Arabia " },
URY: {fillKey: 'URY', visitors: 8, country: " Uruguay " },
HKG: {fillKey: 'HKG', visitors: 101, country: " Hong Kong " },
ISL: {fillKey: 'ISL', visitors: 6, country: " Iceland " },
TJK: {fillKey: 'TJK', visitors: 5, country: " Tajikistan " },
TWN: {fillKey: 'TWN', visitors: 223, country: " Taiwan, Province of China " },
SDN: {fillKey: 'SDN', visitors: 1, country: " Sudan " },
CUW: {fillKey: 'CUW', visitors: 1, country: " Curaçao " },
POL: {fillKey: 'POL', visitors: 301, country: " Poland " },
MKD: {fillKey: 'MKD', visitors: 2, country: " Macedonia, Republic of " },
SVN: {fillKey: 'SVN', visitors: 30, country: " Slovenia " },
GUY: {fillKey: 'GUY', visitors: 1, country: " Guyana " },
AZE: {fillKey: 'AZE', visitors: 3, country: " Azerbaijan " },
RUS: {fillKey: 'RUS', visitors: 344, country: " Russian Federation " },
HRV: {fillKey: 'HRV', visitors: 38, country: " Croatia " },
CRI: {fillKey: 'CRI', visitors: 10, country: " Costa Rica " },
EST: {fillKey: 'EST', visitors: 14, country: " Estonia " },
BLR: {fillKey: 'BLR', visitors: 12, country: " Belarus " },
KEN: {fillKey: 'KEN', visitors: 25, country: " Kenya " },
MAR: {fillKey: 'MAR', visitors: 39, country: " Morocco " },
MDG: {fillKey: 'MDG', visitors: 1, country: " Madagascar " },
MUS: {fillKey: 'MUS', visitors: 4, country: " Mauritius " },
PHL: {fillKey: 'PHL', visitors: 67, country: " Philippines " },
IDN: {fillKey: 'IDN', visitors: 51, country: " Indonesia " },
AUT: {fillKey: 'AUT', visitors: 408, country: " Austria " },
IRQ: {fillKey: 'IRQ', visitors: 10, country: " Iraq " },
MLT: {fillKey: 'MLT', visitors: 18, country: " Malta " },
HUN: {fillKey: 'HUN', visitors: 84, country: " Hungary " },
PRI: {fillKey: 'PRI', visitors: 13, country: " Puerto Rico " },
BRA: {fillKey: 'BRA', visitors: 983, country: " Brazil " },
GBR: {fillKey: 'GBR', visitors: 2143, country: " United Kingdom " },
BIH: {fillKey: 'BIH', visitors: 5, country: " Bosnia and Herzegovina " },
PAN: {fillKey: 'PAN', visitors: 3, country: " Panama " },
MAC: {fillKey: 'MAC', visitors: 4, country: " Macao " },
MDA: {fillKey: 'MDA', visitors: 4, country: " Moldova, Republic of " },
CHL: {fillKey: 'CHL', visitors: 104, country: " Chile " },
BEN: {fillKey: 'BEN', visitors: 2, country: " Benin " },
CAN: {fillKey: 'CAN', visitors: 989, country: " Canada " },
BOL: {fillKey: 'BOL', visitors: 21, country: " Bolivia, Plurinational State of " },
TZA: {fillKey: 'TZA', visitors: 3, country: " Tanzania, United Republic of " },
REU: {fillKey: 'REU', visitors: 1, country: " Réunion " },
DOM: {fillKey: 'DOM', visitors: 4, country: " Dominican Republic " },
GRC: {fillKey: 'GRC', visitors: 74, country: " Greece " },
DEU: {fillKey: 'DEU', visitors: 2732, country: " Germany " },
VNM: {fillKey: 'VNM', visitors: 33, country: " Viet Nam " },
MLI: {fillKey: 'MLI', visitors: 2, country: " Mali " },
ESP: {fillKey: 'ESP', visitors: 489, country: " Spain " },
KAZ: {fillKey: 'KAZ', visitors: 5, country: " Kazakhstan " },
TUR: {fillKey: 'TUR', visitors: 334, country: " Turkey " },
DMA: {fillKey: 'DMA', visitors: 1, country: " Dominica " },
MEX: {fillKey: 'MEX', visitors: 360, country: " Mexico " },
KWT: {fillKey: 'KWT', visitors: 4, country: " Kuwait " },
ISR: {fillKey: 'ISR', visitors: 270, country: " Israel " },
NGA: {fillKey: 'NGA', visitors: 9, country: " Nigeria " },
ARM: {fillKey: 'ARM', visitors: 6, country: " Armenia " },
TKM: {fillKey: 'TKM', visitors: 1, country: " Turkmenistan " },
CHE: {fillKey: 'CHE', visitors: 559, country: " Switzerland " },
LBR: {fillKey: 'LBR', visitors: 1, country: " Liberia " },
EGY: {fillKey: 'EGY', visitors: 70, country: " Egypt " },
GHA: {fillKey: 'GHA', visitors: 9, country: " Ghana " },
ARG: {fillKey: 'ARG', visitors: 92, country: " Argentina " },
LBN: {fillKey: 'LBN', visitors: 2, country: " Lebanon " },
SGP: {fillKey: 'SGP', visitors: 279, country: " Singapore " },
LBY: {fillKey: 'LBY', visitors: 2, country: " Libya " },
THA: {fillKey: 'THA', visitors: 46, country: " Thailand " },
FRO: {fillKey: 'FRO', visitors: 1, country: " Faroe Islands " },
SVK: {fillKey: 'SVK', visitors: 38, country: " Slovakia " },
NOR: {fillKey: 'NOR', visitors: 64, country: " Norway " },
UKR: {fillKey: 'UKR', visitors: 92, country: " Ukraine " },
IRN: {fillKey: 'IRN', visitors: 206, country: " Iran, Islamic Republic of " },
BGD: {fillKey: 'BGD', visitors: 19, country: " Bangladesh " },
UGA: {fillKey: 'UGA', visitors: 2, country: " Uganda " },
SWZ: {fillKey: 'SWZ', visitors: 1, country: " Swaziland " },
LSO: {fillKey: 'LSO', visitors: 2, country: " Lesotho " },
SYR: {fillKey: 'SYR', visitors: 2, country: " Syrian Arab Republic " },
ZMB: {fillKey: 'ZMB', visitors: 3, country: " Zambia " },
FIN: {fillKey: 'FIN', visitors: 105, country: " Finland " },
GEO: {fillKey: 'GEO', visitors: 7, country: " Georgia " },
BGR: {fillKey: 'BGR', visitors: 28, country: " Bulgaria " },
HND: {fillKey: 'HND', visitors: 6, country: " Honduras " },
NPL: {fillKey: 'NPL', visitors: 2, country: " Nepal " },
SLV: {fillKey: 'SLV', visitors: 1, country: " El Salvador " },
ROU: {fillKey: 'ROU', visitors: 33, country: " Romania " },
TTO: {fillKey: 'TTO', visitors: 3, country: " Trinidad and Tobago " },
KOR: {fillKey: 'KOR', visitors: 359, country: " Korea, Republic of " },
BHS: {fillKey: 'BHS', visitors: 2, country: " Bahamas " },
DNK: {fillKey: 'DNK', visitors: 234, country: " Denmark " },
ITA: {fillKey: 'ITA', visitors: 516, country: " Italy " },
VEN: {fillKey: 'VEN', visitors: 24, country: " Venezuela, Bolivarian Republic of " },
NIC: {fillKey: 'NIC', visitors: 1, country: " Nicaragua " },
MYS: {fillKey: 'MYS', visitors: 72, country: " Malaysia " },
SRB: {fillKey: 'SRB', visitors: 1, country: " Serbia " },
GRL: {fillKey: 'GRL', visitors: 1, country: " Greenland " },
BHR: {fillKey: 'BHR', visitors: 2, country: " Bahrain " },
MTQ: {fillKey: 'MTQ', visitors: 1, country: " Martinique " },
PER: {fillKey: 'PER', visitors: 27, country: " Peru " },
CHN: {fillKey: 'CHN', visitors: 927, country: " China " },
BLZ: {fillKey: 'BLZ', visitors: 1, country: " Belize " },
NLD: {fillKey: 'NLD', visitors: 476, country: " Netherlands " },
SWE: {fillKey: 'SWE', visitors: 272, country: " Sweden " },
}
})
