
//basic map config with custom fills, mercator projection
var map = new Datamap({
	scope: 'world',
	element: document.getElementById('container1'),
	projection: 'mercator',
	geographyConfig: {
		highlightBorderColor: '#666666',
		popupTemplate: function(geography, data) {
			if (data != null) return "<div class='hoverinfo'>" + geography.properties.name+': '+data.visitors +'</div>'
	},
	highlightBorderWidth: 1
	},
fills: { 
defaultFill: '#CCCCCC', 
USA: '#08306b',
DEU: '#65aad4',
GBR: '#72b2d8',
CHN: '#84bcdb',
IND: '#95c5df',
JPN: '#9cc9e1',
CAN: '#a1cbe2',
FRA: '#a6cee4',
BRA: '#aacfe5',
CHE: '#b3d3e8',
ESP: '#b4d3e9',
ITA: '#b4d3e9',
AUS: '#b5d4e9',
COL: '#b5d4e9',
NLD: '#b7d4ea',
KOR: '#b7d4ea',
RUS: '#b8d5ea',
TUR: '#b8d5ea',
AUT: '#b9d6ea',
SGP: '#bad6eb',
POL: '#bad6eb',
MEX: '#bcd7eb',
SWE: '#bcd7eb',
DNK: '#bdd7ec',
IRN: '#bed8ec',
ISR: '#bed8ec',
TWN: '#bed8ec',
ARG: '#c2d9ee',
BEL: '#c3daee',
FIN: '#c3daee',
GRC: '#c3daee',
CHL: '#c3daee',
CZE: '#c3daee',
HKG: '#c3daee',
PAK: '#c3daee',
NZL: '#c4daee',
ZAF: '#c4daee',
PRT: '#c4daee',
MYS: '#c4daee',
THA: '#c4daee',
EGY: '#c4daee',
HUN: '#c4daee',
NOR: '#c4daee',
ROU: '#c4daee',
IDN: '#c4daee',
SAU: '#c4daee',
IRL: '#c4daee',
UKR: '#c4daee',
MAR: '#c6dbef',
HRV: '#c6dbef',
PER: '#c6dbef',
SRB: '#c7dbef',
PHL: '#c6dbef',
ARE: '#c6dbef',
MLT: '#c6dbef',
VNM: '#c6dbef',
CMR: '#c6dbef',
SVK: '#c6dbef',
DZA: '#c6dbef',
LUX: '#c6dbef',
BLR: '#c6dbef',
ECU: '#c6dbef',
LTU: '#c6dbef',
BGR: '#c6dbef',
TUN: '#c6dbef',
VEN: '#c6dbef',
KEN: '#c7dbef',
KAZ: '#c7dbef',
BGD: '#c7dbef',
SVN: '#c7dbef',
IRQ: '#c7dbef',
KWT: '#c7dbef',
ETH: '#c7dbef',
PRI: '#c7dbef',
SDN: '#c7dbef',
BOL: '#c7dbef',
EST: '#c7dbef',
ISL: '#c7dbef',
LKA: '#c7dbef',
LVA: '#c7dbef',
NGA: '#c7dbef',
ARM: '#c7dbef',
CYP: '#c7dbef',
GTM: '#c7dbef',
SEN: '#c7dbef',
GEO: '#c7dbef',
ALB: '#c7dbef',
JOR: '#c7dbef',
NPL: '#c7dbef',
QAT: '#c7dbef',
GHA: '#c7dbef',
LBN: '#c7dbef',
MUS: '#c7dbef',
OMN: '#c7dbef',
TZA: '#c7dbef',
CUB: '#c7dbef',
URY: '#c7dbef',
MKD: '#c7dbef',
PSE: '#c7dbef',
UGA: '#c7dbef',
BIH: '#c7dbef',
BDI: '#c7dbef',
BEN: '#c7dbef',
BMU: '#c7dbef',
DOM: '#c7dbef',
HND: '#c7dbef',
JAM: '#c7dbef',
MDA: '#c7dbef',
MAC: '#c7dbef',
NIC: '#c7dbef',
PAN: '#c7dbef',
YEM: '#c7dbef',
ZMB: '#c7dbef',
AFG: '#c7dbef',
ALA: '#c7dbef',
AZE: '#c7dbef',
BRB: '#c7dbef',
BHR: '#c7dbef',
BHS: '#c7dbef',
BTN: '#c7dbef',
BLZ: '#c7dbef',
CUW: '#c7dbef',
DMA: '#c7dbef',
HTI: '#c7dbef',
JEY: '#c7dbef',
KHM: '#c7dbef',
CYM: '#c7dbef',
LIE: '#c7dbef',
MDG: '#c7dbef',
MTQ: '#c7dbef',
PRY: '#c7dbef',
REU: '#c7dbef',
SLV: '#c7dbef',
SYR: '#c7dbef',
TJK: '#c7dbef',
TKM: '#c7dbef',
UZB: '#c7dbef',
},data: { 
USA: {fillKey: 'USA', visitors: 6185, country: " United States " },
DEU: {fillKey: 'DEU', visitors: 2209, country: " Germany " },
GBR: {fillKey: 'GBR', visitors: 1924, country: " United Kingdom " },
CHN: {fillKey: 'CHN', visitors: 1586, country: " China " },
IND: {fillKey: 'IND', visitors: 1235, country: " India " },
JPN: {fillKey: 'JPN', visitors: 1102, country: " Japan " },
CAN: {fillKey: 'CAN', visitors: 951, country: " Canada " },
FRA: {fillKey: 'FRA', visitors: 828, country: " France " },
BRA: {fillKey: 'BRA', visitors: 749, country: " Brazil " },
CHE: {fillKey: 'CHE', visitors: 501, country: " Switzerland " },
ESP: {fillKey: 'ESP', visitors: 493, country: " Spain " },
ITA: {fillKey: 'ITA', visitors: 479, country: " Italy " },
AUS: {fillKey: 'AUS', visitors: 448, country: " Australia " },
COL: {fillKey: 'COL', visitors: 440, country: " Colombia " },
NLD: {fillKey: 'NLD', visitors: 415, country: " Netherlands " },
KOR: {fillKey: 'KOR', visitors: 413, country: " Korea, Republic of " },
RUS: {fillKey: 'RUS', visitors: 390, country: " Russian Federation " },
TUR: {fillKey: 'TUR', visitors: 386, country: " Turkey " },
AUT: {fillKey: 'AUT', visitors: 351, country: " Austria " },
SGP: {fillKey: 'SGP', visitors: 325, country: " Singapore " },
POL: {fillKey: 'POL', visitors: 314, country: " Poland " },
MEX: {fillKey: 'MEX', visitors: 301, country: " Mexico " },
SWE: {fillKey: 'SWE', visitors: 274, country: " Sweden " },
DNK: {fillKey: 'DNK', visitors: 272, country: " Denmark " },
IRN: {fillKey: 'IRN', visitors: 229, country: " Iran, Islamic Republic of " },
ISR: {fillKey: 'ISR', visitors: 224, country: " Israel " },
TWN: {fillKey: 'TWN', visitors: 218, country: " Taiwan, Province of China " },
ARG: {fillKey: 'ARG', visitors: 112, country: " Argentina " },
BEL: {fillKey: 'BEL', visitors: 106, country: " Belgium " },
FIN: {fillKey: 'FIN', visitors: 103, country: " Finland " },
GRC: {fillKey: 'GRC', visitors: 103, country: " Greece " },
CHL: {fillKey: 'CHL', visitors: 101, country: " Chile " },
CZE: {fillKey: 'CZE', visitors: 101, country: " Czechia " },
HKG: {fillKey: 'HKG', visitors: 84, country: " Hong Kong " },
PAK: {fillKey: 'PAK', visitors: 80, country: " Pakistan " },
NZL: {fillKey: 'NZL', visitors: 78, country: " New Zealand " },
ZAF: {fillKey: 'ZAF', visitors: 75, country: " South Africa " },
PRT: {fillKey: 'PRT', visitors: 74, country: " Portugal " },
MYS: {fillKey: 'MYS', visitors: 72, country: " Malaysia " },
THA: {fillKey: 'THA', visitors: 68, country: " Thailand " },
EGY: {fillKey: 'EGY', visitors: 65, country: " Egypt " },
HUN: {fillKey: 'HUN', visitors: 63, country: " Hungary " },
NOR: {fillKey: 'NOR', visitors: 59, country: " Norway " },
ROU: {fillKey: 'ROU', visitors: 55, country: " Romania " },
IDN: {fillKey: 'IDN', visitors: 54, country: " Indonesia " },
SAU: {fillKey: 'SAU', visitors: 54, country: " Saudi Arabia " },
IRL: {fillKey: 'IRL', visitors: 50, country: " Ireland " },
UKR: {fillKey: 'UKR', visitors: 48, country: " Ukraine " },
MAR: {fillKey: 'MAR', visitors: 44, country: " Morocco " },
HRV: {fillKey: 'HRV', visitors: 40, country: " Croatia " },
PER: {fillKey: 'PER', visitors: 39, country: " Peru " },
SRB: {fillKey: 'SRB', visitors: 3, country: " Serbia " },
PHL: {fillKey: 'PHL', visitors: 35, country: " Philippines " },
ARE: {fillKey: 'ARE', visitors: 31, country: " United Arab Emirates " },
MLT: {fillKey: 'MLT', visitors: 29, country: " Malta " },
VNM: {fillKey: 'VNM', visitors: 29, country: " Viet Nam " },
CMR: {fillKey: 'CMR', visitors: 27, country: " Cameroon " },
SVK: {fillKey: 'SVK', visitors: 25, country: " Slovakia " },
DZA: {fillKey: 'DZA', visitors: 23, country: " Algeria " },
LUX: {fillKey: 'LUX', visitors: 21, country: " Luxembourg " },
BLR: {fillKey: 'BLR', visitors: 20, country: " Belarus " },
ECU: {fillKey: 'ECU', visitors: 18, country: " Ecuador " },
LTU: {fillKey: 'LTU', visitors: 18, country: " Lithuania " },
BGR: {fillKey: 'BGR', visitors: 17, country: " Bulgaria " },
TUN: {fillKey: 'TUN', visitors: 16, country: " Tunisia " },
VEN: {fillKey: 'VEN', visitors: 16, country: " Venezuela, Bolivarian Republic of " },
KEN: {fillKey: 'KEN', visitors: 13, country: " Kenya " },
KAZ: {fillKey: 'KAZ', visitors: 13, country: " Kazakhstan " },
BGD: {fillKey: 'BGD', visitors: 12, country: " Bangladesh " },
SVN: {fillKey: 'SVN', visitors: 12, country: " Slovenia " },
IRQ: {fillKey: 'IRQ', visitors: 11, country: " Iraq " },
KWT: {fillKey: 'KWT', visitors: 11, country: " Kuwait " },
ETH: {fillKey: 'ETH', visitors: 10, country: " Ethiopia " },
PRI: {fillKey: 'PRI', visitors: 10, country: " Puerto Rico " },
SDN: {fillKey: 'SDN', visitors: 10, country: " Sudan " },
BOL: {fillKey: 'BOL', visitors: 9, country: " Bolivia, Plurinational State of " },
EST: {fillKey: 'EST', visitors: 9, country: " Estonia " },
ISL: {fillKey: 'ISL', visitors: 9, country: " Iceland " },
LKA: {fillKey: 'LKA', visitors: 9, country: " Sri Lanka " },
LVA: {fillKey: 'LVA', visitors: 9, country: " Latvia " },
NGA: {fillKey: 'NGA', visitors: 9, country: " Nigeria " },
ARM: {fillKey: 'ARM', visitors: 8, country: " Armenia " },
CYP: {fillKey: 'CYP', visitors: 8, country: " Cyprus " },
GTM: {fillKey: 'GTM', visitors: 8, country: " Guatemala " },
SEN: {fillKey: 'SEN', visitors: 8, country: " Senegal " },
GEO: {fillKey: 'GEO', visitors: 7, country: " Georgia " },
ALB: {fillKey: 'ALB', visitors: 6, country: " Albania " },
JOR: {fillKey: 'JOR', visitors: 6, country: " Jordan " },
NPL: {fillKey: 'NPL', visitors: 6, country: " Nepal " },
QAT: {fillKey: 'QAT', visitors: 6, country: " Qatar " },
GHA: {fillKey: 'GHA', visitors: 5, country: " Ghana " },
LBN: {fillKey: 'LBN', visitors: 5, country: " Lebanon " },
MUS: {fillKey: 'MUS', visitors: 5, country: " Mauritius " },
OMN: {fillKey: 'OMN', visitors: 5, country: " Oman " },
TZA: {fillKey: 'TZA', visitors: 5, country: " Tanzania, United Republic of " },
CUB: {fillKey: 'CUB', visitors: 4, country: " Cuba " },
URY: {fillKey: 'URY', visitors: 4, country: " Uruguay " },
MKD: {fillKey: 'MKD', visitors: 3, country: " Macedonia, Republic of " },
PSE: {fillKey: 'PSE', visitors: 3, country: " Palestine, State of " },
UGA: {fillKey: 'UGA', visitors: 3, country: " Uganda " },
BIH: {fillKey: 'BIH', visitors: 2, country: " Bosnia and Herzegovina " },
BDI: {fillKey: 'BDI', visitors: 2, country: " Burundi " },
BEN: {fillKey: 'BEN', visitors: 2, country: " Benin " },
BMU: {fillKey: 'BMU', visitors: 2, country: " Bermuda " },
DOM: {fillKey: 'DOM', visitors: 2, country: " Dominican Republic " },
HND: {fillKey: 'HND', visitors: 2, country: " Honduras " },
JAM: {fillKey: 'JAM', visitors: 2, country: " Jamaica " },
MDA: {fillKey: 'MDA', visitors: 2, country: " Moldova, Republic of " },
MAC: {fillKey: 'MAC', visitors: 2, country: " Macao " },
NIC: {fillKey: 'NIC', visitors: 2, country: " Nicaragua " },
PAN: {fillKey: 'PAN', visitors: 2, country: " Panama " },
YEM: {fillKey: 'YEM', visitors: 2, country: " Yemen " },
ZMB: {fillKey: 'ZMB', visitors: 2, country: " Zambia " },
AFG: {fillKey: 'AFG', visitors: 1, country: " Afghanistan " },
ALA: {fillKey: 'ALA', visitors: 1, country: " Åland Islands " },
AZE: {fillKey: 'AZE', visitors: 1, country: " Azerbaijan " },
BRB: {fillKey: 'BRB', visitors: 1, country: " Barbados " },
BHR: {fillKey: 'BHR', visitors: 1, country: " Bahrain " },
BHS: {fillKey: 'BHS', visitors: 1, country: " Bahamas " },
BTN: {fillKey: 'BTN', visitors: 1, country: " Bhutan " },
BLZ: {fillKey: 'BLZ', visitors: 1, country: " Belize " },
CUW: {fillKey: 'CUW', visitors: 1, country: " Curaçao " },
DMA: {fillKey: 'DMA', visitors: 1, country: " Dominica " },
HTI: {fillKey: 'HTI', visitors: 1, country: " Haiti " },
JEY: {fillKey: 'JEY', visitors: 1, country: " Jersey " },
KHM: {fillKey: 'KHM', visitors: 1, country: " Cambodia " },
CYM: {fillKey: 'CYM', visitors: 1, country: " Cayman Islands " },
LIE: {fillKey: 'LIE', visitors: 1, country: " Liechtenstein " },
MDG: {fillKey: 'MDG', visitors: 1, country: " Madagascar " },
MTQ: {fillKey: 'MTQ', visitors: 1, country: " Martinique " },
PRY: {fillKey: 'PRY', visitors: 1, country: " Paraguay " },
REU: {fillKey: 'REU', visitors: 1, country: " Réunion " },
SLV: {fillKey: 'SLV', visitors: 1, country: " El Salvador " },
SYR: {fillKey: 'SYR', visitors: 1, country: " Syrian Arab Republic " },
TJK: {fillKey: 'TJK', visitors: 1, country: " Tajikistan " },
TKM: {fillKey: 'TKM', visitors: 1, country: " Turkmenistan " },
UZB: {fillKey: 'UZB', visitors: 1, country: " Uzbekistan " },
}
})
