
//basic map config with custom fills, mercator projection
var map = new Datamap({
    scope: 'world',
    element: document.getElementById('container1'),
    projection: 'mercator',
    geographyConfig: {
        highlightBorderColor: '#666666',
        popupTemplate: function(geography, data) {
            if (data != null) {
                return "<div class='hoverinfo'>" + geography.properties.name
                        + ': ' + data.visitors + '</div>';
            }
    },
    highlightBorderWidth: 1
    },
fills: { 
defaultFill: '#CCCCCC', 
USA: '#08306b',
CHN: '#4090c5',
IND: '#5da5d1',
DEU: '#7cb7da',
GBR: '#8abfdd',
JPN: '#8cc0dd',
BRA: '#a9cfe5',
FRA: '#a9cfe5',
CAN: '#a9cfe5',
ITA: '#afd1e7',
ESP: '#b0d2e7',
RUS: '#b3d3e8',
KOR: '#b3d3e8',
AUS: '#b5d4e9',
CHE: '#b5d4e9',
TWN: '#b8d5ea',
NLD: '#b8d5ea',
TUR: '#b9d6ea',
POL: '#bad6eb',
SGP: '#bad6eb',
HKG: '#bad6eb',
IRN: '#bcd7eb',
SWE: '#bcd7eb',
AUT: '#bdd7ec',
MEX: '#bdd7ec',
ISR: '#bdd7ec',
COL: '#bfd8ed',
DNK: '#bfd8ed',
ARG: '#c2d9ee',
BEL: '#c2d9ee',
IDN: '#c2d9ee',
EGY: '#c2d9ee',
FIN: '#c2d9ee',
CHL: '#c2d9ee',
PAK: '#c2d9ee',
XXX: '#c2d9ee',
THA: '#c2d9ee',
IRL: '#c2d9ee',
GRC: '#c2d9ee',
CMR: '#c3daee',
UKR: '#c3daee',
CZE: '#c3daee',
ZAF: '#c3daee',
ROU: '#c3daee',
MYS: '#c4daee',
ARE: '#c4daee',
PRT: '#c4daee',
NOR: '#c4daee',
MAR: '#c4daee',
HUN: '#c4daee',
NZL: '#c4daee',
NPL: '#c4daee',
PER: '#c4daee',
BGD: '#c4daee',
SAU: '#c6dbef',
PHL: '#c6dbef',
VNM: '#c6dbef',
DZA: '#c6dbef',
SRB: '#c7dbef',
BGR: '#c6dbef',
NGA: '#c6dbef',
SVK: '#c6dbef',
SVN: '#c6dbef',
IRQ: '#c6dbef',
TUN: '#c6dbef',
BLR: '#c6dbef',
HRV: '#c6dbef',
KEN: '#c6dbef',
EST: '#c7dbef',
ARM: '#c7dbef',
VEN: '#c7dbef',
ECU: '#c7dbef',
KAZ: '#c7dbef',
LKA: '#c7dbef',
ISL: '#c7dbef',
LBN: '#c7dbef',
LUX: '#c7dbef',
URY: '#c7dbef',
CRI: '#c7dbef',
LVA: '#c7dbef',
QAT: '#c7dbef',
UZB: '#c7dbef',
GEO: '#c7dbef',
LTU: '#c7dbef',
CUB: '#c7dbef',
GHA: '#c7dbef',
MDA: '#c7dbef',
MMR: '#c7dbef',
PSE: '#c7dbef',
JOR: '#c7dbef',
KHM: '#c7dbef',
MLT: '#c7dbef',
SDN: '#c7dbef',
CYP: '#c7dbef',
MKD: '#c7dbef',
PAN: '#c7dbef',
PRI: '#c7dbef',
AZE: '#c7dbef',
DOM: '#c7dbef',
ETH: '#c7dbef',
SYR: '#c7dbef',
LSO: '#c7dbef',
LBY: '#c7dbef',
OMN: '#c7dbef',
SLV: '#c7dbef',
ALB: '#c7dbef',
BOL: '#c7dbef',
CIV: '#c7dbef',
MAC: '#c7dbef',
NAM: '#c7dbef',
PRY: '#c7dbef',
UGA: '#c7dbef',
BIH: '#c7dbef',
KGZ: '#c7dbef',
AGO: '#c7dbef',
BHR: '#c7dbef',
GTM: '#c7dbef',
KWT: '#c7dbef',
MOZ: '#c7dbef',
NIC: '#c7dbef',
REU: '#c7dbef',
SEN: '#c7dbef',
TTO: '#c7dbef',
AFG: '#c7dbef',
BWA: '#c7dbef',
GRD: '#c7dbef',
MNE: '#c7dbef',
MNG: '#c7dbef',
YEM: '#c7dbef',
ATG: '#c7dbef',
BTN: '#c7dbef',
FJI: '#c7dbef',
GAB: '#c7dbef',
GMB: '#c7dbef',
GLP: '#c7dbef',
HND: '#c7dbef',
LAO: '#c7dbef',
LIE: '#c7dbef',
MDG: '#c7dbef',
MUS: '#c7dbef',
NER: '#c7dbef',
RWA: '#c7dbef',
SYC: '#c7dbef',
SOM: '#c7dbef',
TGO: '#c7dbef',
TJK: '#c7dbef',
TZA: '#c7dbef',
ZMB: '#c7dbef',
},data: { 
USA: {fillKey: 'USA', visitors: 8474, country: ' United States '},
CHN: {fillKey: 'CHN', visitors: 4329, country: ' China '},
IND: {fillKey: 'IND', visitors: 3305, country: ' India '},
DEU: {fillKey: 'DEU', visitors: 2396, country: ' Germany '},
GBR: {fillKey: 'GBR', visitors: 1992, country: ' United Kingdom '},
JPN: {fillKey: 'JPN', visitors: 1928, country: ' Japan '},
BRA: {fillKey: 'BRA', visitors: 1071, country: ' Brazil '},
FRA: {fillKey: 'FRA', visitors: 1054, country: ' France '},
CAN: {fillKey: 'CAN', visitors: 1040, country: ' Canada '},
ITA: {fillKey: 'ITA', visitors: 827, country: ' Italy '},
ESP: {fillKey: 'ESP', visitors: 783, country: ' Spain '},
RUS: {fillKey: 'RUS', visitors: 709, country: ' Russian Federation '},
KOR: {fillKey: 'KOR', visitors: 702, country: ' Korea, Republic of '},
AUS: {fillKey: 'AUS', visitors: 603, country: ' Australia '},
CHE: {fillKey: 'CHE', visitors: 603, country: ' Switzerland '},
TWN: {fillKey: 'TWN', visitors: 536, country: ' Taiwan, Province of China '},
NLD: {fillKey: 'NLD', visitors: 520, country: ' Netherlands '},
TUR: {fillKey: 'TUR', visitors: 486, country: ' Turkey '},
POL: {fillKey: 'POL', visitors: 446, country: ' Poland '},
SGP: {fillKey: 'SGP', visitors: 421, country: ' Singapore '},
HKG: {fillKey: 'HKG', visitors: 420, country: ' Hong Kong '},
IRN: {fillKey: 'IRN', visitors: 404, country: ' Iran, Islamic Republic of '},
SWE: {fillKey: 'SWE', visitors: 386, country: ' Sweden '},
AUT: {fillKey: 'AUT', visitors: 373, country: ' Austria '},
MEX: {fillKey: 'MEX', visitors: 368, country: ' Mexico '},
ISR: {fillKey: 'ISR', visitors: 349, country: ' Israel '},
COL: {fillKey: 'COL', visitors: 282, country: ' Colombia '},
DNK: {fillKey: 'DNK', visitors: 257, country: ' Denmark '},
ARG: {fillKey: 'ARG', visitors: 189, country: ' Argentina '},
BEL: {fillKey: 'BEL', visitors: 178, country: ' Belgium '},
IDN: {fillKey: 'IDN', visitors: 173, country: ' Indonesia '},
EGY: {fillKey: 'EGY', visitors: 169, country: ' Egypt '},
FIN: {fillKey: 'FIN', visitors: 169, country: ' Finland '},
CHL: {fillKey: 'CHL', visitors: 168, country: ' Chile '},
PAK: {fillKey: 'PAK', visitors: 166, country: ' Pakistan '},
XXX: {fillKey: 'XXX', visitors: 166, country: ' Unknown '},
THA: {fillKey: 'THA', visitors: 162, country: ' Thailand '},
IRL: {fillKey: 'IRL', visitors: 158, country: ' Ireland '},
GRC: {fillKey: 'GRC', visitors: 156, country: ' Greece '},
CMR: {fillKey: 'CMR', visitors: 120, country: ' Cameroon '},
UKR: {fillKey: 'UKR', visitors: 117, country: ' Ukraine '},
CZE: {fillKey: 'CZE', visitors: 116, country: ' Czechia '},
ZAF: {fillKey: 'ZAF', visitors: 111, country: ' South Africa '},
ROU: {fillKey: 'ROU', visitors: 110, country: ' Romania '},
MYS: {fillKey: 'MYS', visitors: 102, country: ' Malaysia '},
ARE: {fillKey: 'ARE', visitors: 101, country: ' United Arab Emirates '},
PRT: {fillKey: 'PRT', visitors: 89, country: ' Portugal '},
NOR: {fillKey: 'NOR', visitors: 85, country: ' Norway '},
MAR: {fillKey: 'MAR', visitors: 84, country: ' Morocco '},
HUN: {fillKey: 'HUN', visitors: 82, country: ' Hungary '},
NZL: {fillKey: 'NZL', visitors: 80, country: ' New Zealand '},
NPL: {fillKey: 'NPL', visitors: 71, country: ' Nepal '},
PER: {fillKey: 'PER', visitors: 69, country: ' Peru '},
BGD: {fillKey: 'BGD', visitors: 66, country: ' Bangladesh '},
SAU: {fillKey: 'SAU', visitors: 62, country: ' Saudi Arabia '},
PHL: {fillKey: 'PHL', visitors: 61, country: ' Philippines '},
VNM: {fillKey: 'VNM', visitors: 61, country: ' Viet Nam '},
DZA: {fillKey: 'DZA', visitors: 57, country: ' Algeria '},
SRB: {fillKey: 'SRB', visitors: 4, country: ' Serbia '},
BGR: {fillKey: 'BGR', visitors: 43, country: ' Bulgaria '},
NGA: {fillKey: 'NGA', visitors: 38, country: ' Nigeria '},
SVK: {fillKey: 'SVK', visitors: 37, country: ' Slovakia '},
SVN: {fillKey: 'SVN', visitors: 32, country: ' Slovenia '},
IRQ: {fillKey: 'IRQ', visitors: 30, country: ' Iraq '},
TUN: {fillKey: 'TUN', visitors: 28, country: ' Tunisia '},
BLR: {fillKey: 'BLR', visitors: 27, country: ' Belarus '},
HRV: {fillKey: 'HRV', visitors: 24, country: ' Croatia '},
KEN: {fillKey: 'KEN', visitors: 24, country: ' Kenya '},
EST: {fillKey: 'EST', visitors: 21, country: ' Estonia '},
ARM: {fillKey: 'ARM', visitors: 20, country: ' Armenia '},
VEN: {fillKey: 'VEN', visitors: 19, country: ' Venezuela, Bolivarian Republic of '},
ECU: {fillKey: 'ECU', visitors: 18, country: ' Ecuador '},
KAZ: {fillKey: 'KAZ', visitors: 18, country: ' Kazakhstan '},
LKA: {fillKey: 'LKA', visitors: 17, country: ' Sri Lanka '},
ISL: {fillKey: 'ISL', visitors: 16, country: ' Iceland '},
LBN: {fillKey: 'LBN', visitors: 16, country: ' Lebanon '},
LUX: {fillKey: 'LUX', visitors: 16, country: ' Luxembourg '},
URY: {fillKey: 'URY', visitors: 15, country: ' Uruguay '},
CRI: {fillKey: 'CRI', visitors: 14, country: ' Costa Rica '},
LVA: {fillKey: 'LVA', visitors: 13, country: ' Latvia '},
QAT: {fillKey: 'QAT', visitors: 13, country: ' Qatar '},
UZB: {fillKey: 'UZB', visitors: 13, country: ' Uzbekistan '},
GEO: {fillKey: 'GEO', visitors: 11, country: ' Georgia '},
LTU: {fillKey: 'LTU', visitors: 11, country: ' Lithuania '},
CUB: {fillKey: 'CUB', visitors: 10, country: ' Cuba '},
GHA: {fillKey: 'GHA', visitors: 10, country: ' Ghana '},
MDA: {fillKey: 'MDA', visitors: 10, country: ' Moldova, Republic of '},
MMR: {fillKey: 'MMR', visitors: 10, country: ' Myanmar '},
PSE: {fillKey: 'PSE', visitors: 10, country: ' Palestine, State of '},
JOR: {fillKey: 'JOR', visitors: 9, country: ' Jordan '},
KHM: {fillKey: 'KHM', visitors: 9, country: ' Cambodia '},
MLT: {fillKey: 'MLT', visitors: 9, country: ' Malta '},
SDN: {fillKey: 'SDN', visitors: 9, country: ' Sudan '},
CYP: {fillKey: 'CYP', visitors: 8, country: ' Cyprus '},
MKD: {fillKey: 'MKD', visitors: 8, country: ' North Macedonia '},
PAN: {fillKey: 'PAN', visitors: 8, country: ' Panama '},
PRI: {fillKey: 'PRI', visitors: 8, country: ' Puerto Rico '},
AZE: {fillKey: 'AZE', visitors: 7, country: ' Azerbaijan '},
DOM: {fillKey: 'DOM', visitors: 7, country: ' Dominican Republic '},
ETH: {fillKey: 'ETH', visitors: 7, country: ' Ethiopia '},
SYR: {fillKey: 'SYR', visitors: 7, country: ' Syrian Arab Republic '},
LSO: {fillKey: 'LSO', visitors: 6, country: ' Lesotho '},
LBY: {fillKey: 'LBY', visitors: 6, country: ' Libya '},
OMN: {fillKey: 'OMN', visitors: 6, country: ' Oman '},
SLV: {fillKey: 'SLV', visitors: 6, country: ' El Salvador '},
ALB: {fillKey: 'ALB', visitors: 5, country: ' Albania '},
BOL: {fillKey: 'BOL', visitors: 5, country: ' Bolivia, Plurinational State of '},
CIV: {fillKey: 'CIV', visitors: 5, country: ' Côte d'Ivoire '},
MAC: {fillKey: 'MAC', visitors: 5, country: ' Macao '},
NAM: {fillKey: 'NAM', visitors: 5, country: ' Namibia '},
PRY: {fillKey: 'PRY', visitors: 5, country: ' Paraguay '},
UGA: {fillKey: 'UGA', visitors: 5, country: ' Uganda '},
BIH: {fillKey: 'BIH', visitors: 4, country: ' Bosnia and Herzegovina '},
KGZ: {fillKey: 'KGZ', visitors: 4, country: ' Kyrgyzstan '},
AGO: {fillKey: 'AGO', visitors: 3, country: ' Angola '},
BHR: {fillKey: 'BHR', visitors: 3, country: ' Bahrain '},
GTM: {fillKey: 'GTM', visitors: 3, country: ' Guatemala '},
KWT: {fillKey: 'KWT', visitors: 3, country: ' Kuwait '},
MOZ: {fillKey: 'MOZ', visitors: 3, country: ' Mozambique '},
NIC: {fillKey: 'NIC', visitors: 3, country: ' Nicaragua '},
REU: {fillKey: 'REU', visitors: 3, country: ' Réunion '},
SEN: {fillKey: 'SEN', visitors: 3, country: ' Senegal '},
TTO: {fillKey: 'TTO', visitors: 3, country: ' Trinidad and Tobago '},
AFG: {fillKey: 'AFG', visitors: 2, country: ' Afghanistan '},
BWA: {fillKey: 'BWA', visitors: 2, country: ' Botswana '},
GRD: {fillKey: 'GRD', visitors: 2, country: ' Grenada '},
MNE: {fillKey: 'MNE', visitors: 2, country: ' Montenegro '},
MNG: {fillKey: 'MNG', visitors: 2, country: ' Mongolia '},
YEM: {fillKey: 'YEM', visitors: 2, country: ' Yemen '},
ATG: {fillKey: 'ATG', visitors: 1, country: ' Antigua and Barbuda '},
BTN: {fillKey: 'BTN', visitors: 1, country: ' Bhutan '},
FJI: {fillKey: 'FJI', visitors: 1, country: ' Fiji '},
GAB: {fillKey: 'GAB', visitors: 1, country: ' Gabon '},
GMB: {fillKey: 'GMB', visitors: 1, country: ' Gambia '},
GLP: {fillKey: 'GLP', visitors: 1, country: ' Guadeloupe '},
HND: {fillKey: 'HND', visitors: 1, country: ' Honduras '},
LAO: {fillKey: 'LAO', visitors: 1, country: ' Lao People's Democratic Republic '},
LIE: {fillKey: 'LIE', visitors: 1, country: ' Liechtenstein '},
MDG: {fillKey: 'MDG', visitors: 1, country: ' Madagascar '},
MUS: {fillKey: 'MUS', visitors: 1, country: ' Mauritius '},
NER: {fillKey: 'NER', visitors: 1, country: ' Niger '},
RWA: {fillKey: 'RWA', visitors: 1, country: ' Rwanda '},
SYC: {fillKey: 'SYC', visitors: 1, country: ' Seychelles '},
SOM: {fillKey: 'SOM', visitors: 1, country: ' Somalia '},
TGO: {fillKey: 'TGO', visitors: 1, country: ' Togo '},
TJK: {fillKey: 'TJK', visitors: 1, country: ' Tajikistan '},
TZA: {fillKey: 'TZA', visitors: 1, country: ' Tanzania, United Republic of '},
ZMB: {fillKey: 'ZMB', visitors: 1, country: ' Zambia '},
}
})
