file_data_store('expect.dat', output_data.T, numtype="real")
with open("expect.dat", "r") as f:
   print('\n'.join(f.readlines()[:5]))
# # Generated by QuTiP: 100x4 real matrix in decimal format [',' separated values].
# 0.0000000000,3.2109553666,0.3689771549,0.0185002867
# 1.0101010101,2.6754598872,0.1298251132,-0.3303672956
# 2.0202020202,2.2743186810,-0.2106241300,-0.2623894277
# 3.0303030303,1.9726633457,-0.3037311621,0.0397330921
